<template>
    <SectionsHome2Section1/>
    <SectionsHome2Section2/>
    <SectionsHome2Section3/>
    <SectionsHome2Section4/>
    <SectionsHome2Section5/>
    <SectionsHome2Section6/>
    <SectionsHome2Section7/>
    <SectionsHome2Section8/>
    <SectionsHome2Section9/>
    <SectionsHome2Section10/>
    <SectionsHome2Section11/>
    <SectionsHome2Section12/>
    <SectionsHome2Section13/>
    <SectionsHome2Section14/>
    <SectionsHome2Section15/>
    <SectionsHome2Section16/>
</template>